# --- GLOBAL SETTINGS ---
data:
  data_to_db: "C:/Users/mmh/Documents/Technical Resources Found by ORNL" # could be just temporary path for data ingestion
  db_path: "C:/Users/mmh/Documents/energy_efficiency_resource_search/chroma_db"
  chunk_size: 256
  chunk_overlap: 40

retrieval:
  num_docs: 5
  chunks_per_doc: 2
  active_db: "demo"
  active_embedding: "mini_lm"

generation:
  active_student: "groq_llama"

llm:
  gemini_pro:
    provider: "gemini"
    model: "gemini-2.5-flash"
  gemini_flash:
    provider: "gemini"
    model: "gemini-2.0-flash"
  openai_mini:
    provider: "openai"
    model: "gpt-4o-mini" # # https://platform.openai.com/docs/pricing
  groq_llama:
    provider: "groq"
    model: "meta-llama/llama-4-maverick-17b-128e-instruct" # https://console.groq.com/docs/rate-limits
  anthropics:
    provider: "anthropic"
    model: "claude-3-haiku-20240307" # https://platform.claude.com/docs/en/about-claude/pricing


embeddings:
  mini_lm:
    model: "sentence-transformers/all-MiniLM-L6-v2"
  gte:
    model: "thenlper/gte-small"
  bge:
    model: "BAAI/bge-small-en-v1.5"
  e5:
    model: "intfloat/e5-small-v2"
  snowflake:
    model: "Snowflake/snowflake-arctic-embed-xs"

db:
  demo:
    collection: "meera-demo"